CREATE DATABASE escola CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE escola;

CREATE TABLE aluno (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	endereco VARCHAR(100) NOT NULL,
	data_nasc DATE NOT NULL
)ENGINE=INNODB COLLATE utf8mb4_unicode_ci;